### ISSUE TITLE
Hello, what does it do?

### ISSUE THREAD

**Issue by hadaev8** [SETNAHQ/Reika#4]

**Comment by saki7** [comment]
Sorry, but that's not a question.

**Comment by hadaev8** [comment]
Okay: where can I read about what it does?

**Comment by saki7** [comment]
https://github.com/SETNAHQ/Reika/blob/master/Reika.rb

**Comment by hadaev8** [comment]
Have you natural language readme or something?

**Comment by saki7** [comment]
No.

Honestly: where on earth did you find this repo itself? You shouldn't be asking "what does this repo do?" kind of questions to every single repo, you know. What are you actually trying to achieve in this repo, really?

**Comment by hadaev8** [comment]
Mm, why not?
I came from google by "discord bot steam workshop" and wonder what i find.

**Comment by hadaev8** [comment]
Usually I don’t need to ask what it does, because there is a readme explane what it does.

**Comment by saki7** [comment]
What you're saying right now is essentially equal to: "You (@saki7) must write README for your repo"

That is not usually a good way to obtain some help from the repo author.
